CREATE DATABASE [BrawlStars]
GO
USE [BrawlStars]
GO
CREATE TABLE [User]
(
	[ID] INT PRIMARY KEY IDENTITY NOT NULL,
	[Login] NVARCHAR (30) NOT NULL,
	[Password] NVARCHAR (30) NOT NULL,
	[Email] NVARCHAR (30) NOT NULL,
	[Level] INT NOT NULL,
)
GO
CREATE TABLE [Trophies]
(
	[ID] INT PRIMARY KEY IDENTITY NOT NULL,
	[IDTrophies] INT FOREIGN KEY REFERENCES [User](ID),
	[Quantity] INT NOT NULL,
)
GO
CREATE TABLE [Characters]
(
	[ID] INT PRIMARY KEY IDENTITY NOT NULL,
	[IDCharacters] INT FOREIGN KEY REFERENCES [User](ID) NOT NULL,
	[CharactersName] NVARCHAR (30) NOT NULL,
	[PowerLevel] INT NOT NULL,
	
)
GO
CREATE TABLE [Discription]
(
	[ID] INT PRIMARY KEY IDENTITY NOT NULL,
	[IDDiscription] INT FOREIGN KEY REFERENCES [Characters](ID) NOT NULL,
	[Discription] NVARCHAR (200) NOT NULL,
)
GO
CREATE TABLE [StarPower]
(
	[ID] INT PRIMARY KEY IDENTITY NOT NULL,
	[IDStarPower] INT FOREIGN KEY REFERENCES [Characters](ID) NOT NULL,
	[StarPower] INT  NOT NULL,
)
GO
CREATE TABLE [Gadget]
(
	[ID] INT PRIMARY KEY IDENTITY NOT NULL,
	[IDGadget] INT FOREIGN KEY REFERENCES [Characters](ID) NOT NULL,
	[Gadget] NVARCHAR (100)  NOT NULL,
)

